main: "jp.jyn.mecon.Mecon"
name: "Mecon"
version: "${project.version}"
website: "${project.url}"
author: "HimaJyun( https://jyn.jp/ )"
description: "${project.description}"
load: "STARTUP"
loadbefore: ["Vault"]
api-version: "1.15"

commands:
  mecon:
    description: "/mecon help - Show helps."
    aliases: "money"

permissions:
  mecon.*:
    children:
      mecon.show: true
      mecon.pay: true
      mecon.show.other: true
      mecon.set: true
      mecon.give: true
      mecon.take: true
      mecon.create: true
      mecon.remove: true
      mecon.top: true
      mecon.convert: true
      mecon.reload: true
      mecon.version: true
  mecon.user:
    children:
      mecon.show: true
      mecon.pay: true
  mecon.op:
    children:
      mecon.show.other: true
      mecon.set: true
      mecon.give: true
      mecon.take: true
      mecon.create: true
      mecon.remove: true
      mecon.top: true
      mecon.convert: true
      mecon.reload: true
      mecon.version: true
  mecon.show:
    default: true
  mecon.pay:
    default: true
  mecon.show.other:
    default: op
  mecon.set:
    default: op
  mecon.give:
    default: op
  mecon.take:
    default: op
  mecon.create:
    default: op
  mecon.remove:
    default: op
  mecon.top:
    default: op
  mecon.convert:
    default: op
  mecon.reload:
    default: op
  mecon.version:
    default: op
